from_latest_tag = false
ignore_merge_commits = false
ignore_fixup_commits = false
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = []
pre = "alpha.*"
tag_prefix = "v"
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
  "sed -i 's/^version = \".*\"/version = \"{{version}}\"/' pyproject.toml",
  "sed -i 's/^__version__ = \".*\"/__version__ = \"{{version}}\"/' src/d0key/__init__.py",
  "uv lock",
  "uv run pytest --no-cov -q",
]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = [
  { signature = "Jiān", username = "coolDudeRude" },
]

[bump_profiles]
